### ISSUE TITLE
Question about the feature level GMM

### ISSUE THREAD

**Issue by Jo-wang** [Jhyun17/CoWA-JMDS#1]
Hi there,
Thank you for your great work.
I am interested in how feature level GMM. In your code, it seems like you are using the feature comes from netB (network.feat_bottleneck) as the GMM input. What if we just grab the classification layer of the network as the GMM input? Will it degrade the performance a lot? Is there any intuition of using feature in this case? 
Thank you!

**Comment by Jhyun17** [comment]
Hi, thank you for your interest in my work.
We use feature-level GMM to extract the target domain knowledge.
It is obvious that the output of netB preserves more target domain knowledge than the output of netC.
That's why we use the feature of netB instead of netC.

I think there will be a performance degradation because the output space of netC does not reflect the target domain knowledge enough due to additional processing related to the source domain knowledge in netC.

Thank you!

**Comment by Jo-wang** [comment]
Thank you for your reply. It seems like the feature-level GMM is not easy to be applied on semantic segmentation since the feature shape is different from the ground-truth label map.
Anyway, thanks a lot.
